// // // no. 1 
// // Write a code to find area of rectangle.
// let panjang = 5
// let lebar = 3
// area = lenght * width
// console.log(area)

// // // no. 2
// // Write a code to find perimeter of rectangle.
// let lenght = 5
// let width = 3
// perimeter = 2*(lenght+width)
// console.log(perimeter)

// // // no. 3
// // Write a code to find diameter, circumference and area of a circle.
// let radius = 5
// let radiusExponential = Math.pow(radius,2)
// diameter = 2*radius
// circumference = 2*Math.PI*radius
// area = Math.PI*radiusExponential
// console.log("diamter = "+ diameter,", circumference = "+ circumference,", area = "+ area)

// // // no. 4
// // Write a code to find angles of triangle if two angles are given.
// let a = 80
// let b = 65
// degrees = 180
// angels = a + b
// console.log(degrees-(a+b))

// // // no. 5
// // // Write a code to convert days to years, months and days (Notes: 1 year : 365 days, 1 month : 30 days).
// let dayInput = 400
// let years = Math.floor(dayInput/365)
// let month = Math.floor(dayInput%365/30)
// let days = (dayInput%365%30)
// console.log(years +" years", month+" month", days+" days")

// // no. 6
// Write a code to get difference between dates in days.
// let date1 = new Date(2022,1,20)
// let date2 = new Date(2022,1,22)
// days = (date1 - date2)
// console.log(Math.abs(days/86400000))
